// Package grpcwrapper provides a production-ready gRPC client and server wrapper
// with built-in connection pooling, retry policies, and TLS support.
package grpcwrapper

import (
	"crypto/tls"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/grpc/keepalive"
)

const (
	// DefaultServiceMaxMsgSize sets the limit for gRPC message transfer to 64MB.
	// This is crucial for components like the Scraper that pull large amounts of traffic data.
	DefaultServiceMaxMsgSize = 1024 * 1024 * 64

	// DefaultClientRetryPolicy defines the standard retry behavior using gRPC's ServiceConfig.
	// It implements exponential backoff and retries on UNAVAILABLE/INTERNAL errors,
	// providing "transparent retries" for the business layer.
	DefaultClientRetryPolicy = `
{
	"methodConfig": [
		{
			"name": [],
			"waitForReady": true,
			"retryPolicy": {
				"MaxAttempts": 5,
				"InitialBackoff": "0.1s",
				"MaxBackoff": "0.5s",
				"BackoffMultiplier": 2.0,
				"RetryableStatusCodes": ["UNAVAILABLE", "INTERNAL"]
			}
		}
	],
	"loadBalancingConfig": [
		{"round_robin": {}},
		{"weighted_round_robin": {}},
		{"pick_first": {"shuffleAddressList": true}}
	]
}`
)

type dialOptions struct {
	retryPolicy        string
	maxMsgSize         int
	unaryInterceptors  []grpc.UnaryClientInterceptor
	streamInterceptors []grpc.StreamClientInterceptor
	useTLS             bool
	insecureSkipVerify bool
}

type DialOption func(*dialOptions)

// WithRetryPolicy sets the custom retry policy in JSON format.
func WithRetryPolicy(p string) DialOption { return func(o *dialOptions) { o.retryPolicy = p } }

// WithMaxMsgSize sets the maximum message size for sending and receiving.
func WithMaxMsgSize(s int) DialOption { return func(o *dialOptions) { o.maxMsgSize = s } }

// WithUnaryInterceptors adds unary interceptors to the client.
func WithUnaryInterceptors(i ...grpc.UnaryClientInterceptor) DialOption {
	return func(o *dialOptions) { o.unaryInterceptors = append(o.unaryInterceptors, i...) }
}

// WithStreamInterceptors adds stream interceptors to the client.
func WithStreamInterceptors(i ...grpc.StreamClientInterceptor) DialOption {
	return func(o *dialOptions) { o.streamInterceptors = append(o.streamInterceptors, i...) }
}

// WithTLS enables standard TLS for the connection (verifies server certificates).
func WithTLS() DialOption { return func(o *dialOptions) { o.useTLS = true } }

// WithInsecure enables TLS but skips certificate verification.
// Useful for self-signed certificates or development environments.
func WithInsecure() DialOption {
	return func(o *dialOptions) {
		o.useTLS = true
		o.insecureSkipVerify = true
	}
}

// newRpcConn creates a new gRPC connection with given settings.
func newRpcConn(addr string, opts ...DialOption) (*grpc.ClientConn, error) {
	do := &dialOptions{
		maxMsgSize:  DefaultServiceMaxMsgSize,
		retryPolicy: DefaultClientRetryPolicy,
	}
	for _, opt := range opts {
		opt(do)
	}

	callOption := grpc.WithDefaultCallOptions(
		grpc.MaxCallRecvMsgSize(do.maxMsgSize),
		grpc.MaxCallSendMsgSize(do.maxMsgSize),
	)

	connectParams := grpc.WithConnectParams(grpc.ConnectParams{
		MinConnectTimeout: time.Second * 3,
	})

	keepaliveParams := grpc.WithKeepaliveParams(keepalive.ClientParameters{
		Time:                time.Second * 10,
		Timeout:             time.Second * 3,
		PermitWithoutStream: true,
	})

	var creds credentials.TransportCredentials
	if do.useTLS {
		creds = credentials.NewTLS(&tls.Config{
			InsecureSkipVerify: do.insecureSkipVerify,
		})
	} else {
		creds = insecure.NewCredentials()
	}

	dialOptions := []grpc.DialOption{
		callOption,
		connectParams,
		keepaliveParams,
		grpc.WithTransportCredentials(creds),
		grpc.WithDefaultServiceConfig(do.retryPolicy),
	}

	for _, interceptor := range do.unaryInterceptors {
		dialOptions = append(dialOptions, grpc.WithUnaryInterceptor(interceptor))
	}
	for _, interceptor := range do.streamInterceptors {
		dialOptions = append(dialOptions, grpc.WithStreamInterceptor(interceptor))
	}

	return grpc.NewClient(addr, dialOptions...)
}

// ClientFactory is a generic function type that wraps the gRPC client constructor.
// E.g., proto.NewControlPlaneServiceClient
type ClientFactory[T any] func(cc grpc.ClientConnInterface) T

// GetClient retrieves a cached connection for the given address and creates a specific gRPC client.
// It uses the provided factory function (generated by protoc-gen-go-grpc).
func GetClient[T any](wrapper *RpcConnWrapper, addr string, factory ClientFactory[T], opts ...DialOption) (T, bool) {
	var zero T
	conn, ok := wrapper.GetConn(addr, opts...)
	if !ok {
		return zero, false
	}
	return factory(conn), true
}
